### ISSUE TITLE
Failed to acquire a JWT token

### ISSUE THREAD

**Issue by chaonan99** [seri/gettc#29]
Got the following error in `initialize` in `download.rb` on Windows 10:

```
$ gettc 14461
F:/Ruby/rb225/ruby/lib/ruby/gems/2.2.0/gems/gettc-2.0/lib/gettc/download.rb:190:in `get_cookie': Failed to acquire a JWT token (Gettc::AuthTokenError)
Account: gettc|algorithm
Server Response:
{
  "error": {
    "name": "Internal Server Error",
    "value": 500,
    "description": "Something is broken. Please contact support.",
    "details": "the connection was disabled"
  },
  "serverInformation": {
    "serverName": "TopCoder API",
    "apiVersion": "0.0.1",
    "requestDuration": 889,
    "currentTime": 1483867621994
  },
  "requesterInformation": {
    "id": "9bbc56f94ec5eec27bcec4172cb29e92c7181ed4-RX2pqfbjnwcPLD3y",
    "remoteIP": "10.250.4.231",
    "receivedParams": {
      "username": "gettc",
      "password": "algorithm",
      "apiVersion": "v2",
      "action": "generateJwt"
    }
  }
}
        from F:/Ruby/rb225/ruby/lib/ruby/gems/2.2.0/gems/gettc-2.0/lib/gettc/download.rb:89:in `initialize'
        from F:/Ruby/rb225/ruby/lib/ruby/gems/2.2.0/gems/gettc-2.0/bin/gettc:36:in `new'
        from F:/Ruby/rb225/ruby/lib/ruby/gems/2.2.0/gems/gettc-2.0/bin/gettc:36:in `init'
        from F:/Ruby/rb225/ruby/lib/ruby/gems/2.2.0/gems/gettc-2.0/bin/gettc:81:in `<top (required)>'
        from F:/Ruby/rb225/ruby/bin/gettc:22:in `load'
        from F:/Ruby/rb225/ruby/bin/gettc:22:in `<main>'

```
Same problem for other IDs.

**Comment by eramirez51** [comment]
I have same problem in Mac

**Comment by babhishek21** [comment]
I am getting the same issue on Mac, except that the failing action is **"refreshJwt"**.

**Comment by seri** [comment]
@babhishek21 @eramirez51 @chaonan99 sorry for the delay guys, i haven't got much time to work on gettc. I've just fixed this issue in gettc 2.1, please try again and let me know if it works for you

**Comment by seri** [comment]
resolved on latest version, closing

**Comment by jlstr** [comment]
@seri Hello there! How can I install the latest version? This problem persists.
